name: Soy
favicon: null
layout_spectrum: 0.27049
typography_spectrum: 0.67965
title: '"Entre los individuos, como entre las Naciones, el respeto al derecho ajeno es la paz"      ~ Benito Juárez'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
