name: Cuauhtémoc Ocampo Badilla
favicon: null
layout_spectrum: 0.25083
typography_spectrum: 0.92879
title: '"Entre los individuos, como entre las Naciones, el respeto al derecho ajeno es la paz" ~ B. Juárez'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010204'
    - '#6800c6'
    - '#a33ffa'
    - '#635d13'
    - '#6684ff'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
