name: Cuauhtémoc Ocampo Badilla
favicon: null
layout_spectrum: 0.98987
typography_spectrum: 0.7039689337834716
title: Cuauhtémoc Ocampo Badilla
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
